version: '3'

services:
    keycloak:
        build: .
        container_name: keycloak_app
        command: 
            -Dkeycloak.profile.feature.upload_scripts=enabled
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=reclame-aqui-realm.json
            - KEYCLOAK_CORS=true
            - REGISTER_URL=http://host.docker.internal:8081/auth
        ports: 
            - 8081:8080