spring:
    data:
        mongodb:
            uri: ${SPRING_DATA_MONGODB_URI}
            #uri: mongodb://localhost:27017/challenge
keycloak:
    cors: true
    realm: reclame-aqui
    auth-server-url: http://host.docker.internal:8081/auth
    ssl-required: external
    resource: challenge-api
    credentials:
        secret: 473ea392-8f28-4ccd-a4f9-f9533a459477
    security-constraints[0]:
        authRoles[0]: admin
        securityCollections[0]:
            patterns[0]: /private/*
    use-resource-role-mappings: true
    bearer-only: true